# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3456144784b075909404d42f7acf34f787a8592a4ef8b75f37900d06fcab645ee775716614ce8cfb1df5b7f9c339e1350311c3bc7c872d4d80be20f6ddcad24

test:
  secret_key_base: a22c4bf9678d161922e6b29c0412bf807112b478af5f88310748a74cb55201e36ed377507f9fdbaeafdb16a03d75156368f3391d2b13bd9b70f01db9a897161d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
